pool-listen = 0.0.0.0
pool-port = 4242
pool-ssl-port =
pool-syn-backlog = 16
webui-listen = 127.0.0.1
webui-port = 4243
rpc-host = 127.0.0.1
rpc-port = 35781
wallet-rpc-host = 127.0.0.1
wallet-rpc-port = 35784
rpc-timeout = 15
idle-timeout = 150
template-timeout = 45
pool-wallet = FDLYPAZzynPP7zchoe6EPKCRKF9WAWbJ4EYP9qREb5jLRqtSYPPojAVQxUuwnu4bFMJHE97YjWPNF8GwJRiBZDXP6tsWizY
pool-fee-wallet = FW9JdoMxySPjQ3xSfFH8zrXc6BTNgJ43eDzw3kr7BccXTW3iaA4STfPfRJySxVB4YwYY9jDDeVqjofAMpuWBVE26LwPJiir
pool-start-diff = 100
pool-fixed-diff = 0
pool-nicehash-diff = 280000
pool-fee = 0.005
payment-threshold = 0.33
share-mul = 2.0
retarget-time = 30
retarget-ratio = 0.55
log-level = 3
log-file =
block-notified = 0
disable-self-select = 1
disable-hash-check = 0
disable-payouts = 0
data-dir = /home/feeladmin/feelcoin-pool-data
pid-file =
forked = 0
processes = 1
cull-shares = -1
# trusted-listen = 127.0.0.1
# trusted-port = 4244
# trusted-allowed = 127.0.0.1,127.0.0.2
# upstream-host = 127.0.0.1
# upstream-port = 4244
# pool-view-key = <hex view key>
